name: 'Deploy Widgetbook'
on:
  push:
    branches:
      - main
    paths:
      - 'widgetbook/**.dart'
  workflow_dispatch: { }

jobs:
  build-widgetbook:
    name: Build Widgetbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Workspace
        uses: ./.github/actions/workspace/setup
      - name: Build Website
        working-directory: widgetbook
        run: flutter build web -t lib/main.dart
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: widgetbook/build/web

  deploy-widgetbook:
    needs: build-widgetbook
    name: Deploy Widgetbook
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "https://github.com/tcht-marie/appliPokedex/actions/runs/11893865872/artifacts"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
